/** Wspólny spis genów i krótkich opisów (indeks HTML + karty do druku). */
window.GENE_INDEX = [
  { gene: "ABCC11", label: "Gen woskowiny usznej", icon: "👂", tone: "amber" },
  { gene: "ACTN3", label: "Gen szybkości", icon: "🏃", tone: "coral" },
  { gene: "ADRA2A", label: "Gen uwagi, skupienia i pamięci roboczej", icon: "🎯", tone: "indigo" },
  { gene: "ALDH2", label: "Gen azjatyckiego rumieńca", icon: "🍶", tone: "rose" },
  { gene: "ANK3", label: "Marker zaburzeń afektywnych", icon: "🌊", tone: "violet" },
  { gene: "ANKK1", label: "Gen poszukiwania nowości", icon: "✨", tone: "purple" },
  { gene: "APOE", label: "Gen Alzheimera", icon: "🧠", tone: "slate" },
  { gene: "AR", label: "Gen męskości", icon: "💪", tone: "steel" },
  { gene: "BDNF", label: "Gen plastyczności mózgu", icon: "🧩", tone: "teal" },
  { gene: "CACNA1C", label: "Gen Timothy'ego", icon: "💓", tone: "pink" },
  { gene: "CDH13", label: "Kadheryna sercowa", icon: "❤️", tone: "crimson" },
  { gene: "CHRNA5", label: "Gen uzależnienia od nikotyny", icon: "🚭", tone: "sage" },
  { gene: "CLOCK", label: "Gen zegara biologicznego", icon: "🕐", tone: "night" },
  { gene: "COMT", label: "Gen Wojownika i Zamartwiacza", icon: "⚔️", tone: "bronze" },
  { gene: "CYP1A2", label: "Gen kofeiny", icon: "☕", tone: "mocha" },
  { gene: "DBH", label: "Gen równowagi stresowej", icon: "⚖️", tone: "mint" },
  { gene: "DRD2", label: "Gen nagrody", icon: "🎁", tone: "gold" },
  { gene: "FKBP5", label: "Gen stresu", icon: "😰", tone: "lavender" },
  { gene: "FTO", label: "Gen otyłości", icon: "⚖️", tone: "peach" },
  { gene: "GC", label: "Gen witaminy D", icon: "☀️", tone: "sun" },
  { gene: "HERC2", label: "Gen niebieskich oczu", icon: "👁️", tone: "sky" },
  { gene: "LCT", label: "Persystencja laktazy", icon: "🥛", tone: "cream" },
  { gene: "MAOA", label: "Gen Wojownika", icon: "🦁", tone: "rust" },
  { gene: "MC1R", label: "Gen rudych włosów", icon: "🦰", tone: "ginger" },
  { gene: "MTHFR", label: "Gen metylacji", icon: "🧬", tone: "forest" },
  { gene: "OCA2", label: "Gen pigmentacji oczu i skóry", icon: "🎨", tone: "tan" },
  { gene: "OR2M", label: "Gen zapachu szparagów", icon: "🌱", tone: "leaf" },
  { gene: "OR6A2", label: "Gen mydlanej kolendry", icon: "🌿", tone: "herb" },
  { gene: "OXTR", label: "Gen hormonu miłości", icon: "💕", tone: "blush" },
  { gene: "SLC24A4", label: "Gen jasnej karnacji", icon: "🌤️", tone: "ivory" },
  { gene: "SLC45A2", label: "Gen jasnej skóry (MATP)", icon: "🧴", tone: "pearl" },
  { gene: "SLC6A4", label: "Gen depresji", icon: "🌧️", tone: "storm" },
  { gene: "TAS2R38", label: "Gen supersmakosza", icon: "👅", tone: "grape" },
  { gene: "TPH2", label: "Gen miłych gości", icon: "😊", tone: "honey" },
  { gene: "ZEB2", label: "Gen naczyń i Mowata-Wilsona", icon: "🩸", tone: "wine" },
];
