/** Wspólny spis genów i krótkich opisów (indeks HTML). */
window.GENE_INDEX = [
  { gene: "ABCC11", label: "Gen woskowiny usznej", icon: "👂", tone: "amber" },
  { gene: "ACTN3", label: "Gen szybkości", icon: "🏃", tone: "coral" },
  { gene: "ADNP", label: "Gen Helsmoortel-Van der Aa", icon: "🧬", tone: "lavender" },
  { gene: "ADRA2A", label: "Gen uwagi, skupienia i pamięci roboczej", icon: "🎯", tone: "indigo" },
  { gene: "ALDH2", label: "Gen azjatyckiego rumieńca", icon: "🍶", tone: "rose" },
  { gene: "ANK3", label: "Marker zaburzeń afektywnych", icon: "🌊", tone: "violet" },
  { gene: "ANKK1", label: "Gen poszukiwania nowości", icon: "✨", tone: "purple" },
  { gene: "APOE", label: "Gen Alzheimera", icon: "🧠", tone: "slate" },
  { gene: "AR", label: "Gen męskości", icon: "💪", tone: "steel" },
  { gene: "AVPR1A", label: "Gen monogamii", icon: "💕", tone: "rose" },
  { gene: "BDNF", label: "Gen plastyczności mózgu", icon: "🧩", tone: "teal" },
  { gene: "CACNA1C", label: "Gen Timothy'ego", icon: "💓", tone: "pink" },
  { gene: "CDH13", label: "Kadheryna sercowa", icon: "❤️", tone: "crimson" },
  { gene: "CHRM2", label: "Gen inteligencji", icon: "🧠", tone: "sky" },
  { gene: "CHRNA5", label: "Gen uzależnienia od nikotyny", icon: "🚭", tone: "sage" },
  { gene: "CLOCK", label: "Gen zegara biologicznego", icon: "🕐", tone: "night" },
  { gene: "CNTNAP2", label: "Gen mowy i autyzmu", icon: "🗣️", tone: "sky" },
  { gene: "COMT", label: "Gen Wojownika i Zamartwiacza", icon: "⚔️", tone: "bronze" },
  { gene: "CYP1A2", label: "Gen kofeiny", icon: "☕", tone: "mocha" },
  { gene: "CYP2C19", label: "Gen Plavix", icon: "💊", tone: "sage" },
  { gene: "CYP2D6", label: "Gen detoksu", icon: "🧪", tone: "forest" },
  { gene: "FADS1", label: "Gen omega-3/omega-6", icon: "🐟", tone: "sage" },
  { gene: "FADS2", label: "Gen karmienia piersią", icon: "🍼", tone: "honey" },
  { gene: "DBH", label: "Gen równowagi stresowej", icon: "⚖️", tone: "mint" },
  { gene: "DRD2", label: "Gen nagrody", icon: "🎁", tone: "gold" },
  { gene: "FKBP5", label: "Gen stresu", icon: "😰", tone: "lavender" },
  { gene: "FMR1", label: "Gen zespołu łamliwego X", icon: "🧩", tone: "indigo" },
  { gene: "FTO", label: "Gen otyłości", icon: "⚖️", tone: "peach" },
  { gene: "GC", label: "Gen witaminy D", icon: "☀️", tone: "sun" },
  { gene: "HERC2", label: "Gen niebieskich oczu", icon: "👁️", tone: "sky" },
  { gene: "IL2RA", label: "Gen autoimmunologii", icon: "🛡️", tone: "mint" },
  { gene: "KCNQ4", label: "Gen słuchu", icon: "👂", tone: "pearl" },
  { gene: "LCT", label: "Persystencja laktazy", icon: "🥛", tone: "cream" },
  { gene: "MAOA", label: "Gen Wojownika", icon: "🦁", tone: "rust" },
  { gene: "MECP2", label: "Gen zespołu Rett", icon: "🧠", tone: "violet" },
  { gene: "MC1R", label: "Gen rudych włosów", icon: "🦰", tone: "ginger" },
  { gene: "MTHFR", label: "Gen metylacji", icon: "🧬", tone: "forest" },
  { gene: "MTR", label: "Gen syntazy metioninowej", icon: "🧬", tone: "forest" },
  { gene: "MTRR", label: "Gen recyklingu B12", icon: "🧬", tone: "forest" },
  { gene: "OCA2", label: "Gen pigmentacji oczu i skóry", icon: "🎨", tone: "tan" },
  { gene: "OR1A1", label: "Gen mięty i cytrusów", icon: "🍃", tone: "herb" },
  { gene: "OR2M", label: "Gen zapachu szparagów", icon: "🌱", tone: "leaf" },
  { gene: "OR6A2", label: "Gen mydlanej kolendry", icon: "🌿", tone: "herb" },
  { gene: "OXTR", label: "Gen hormonu miłości", icon: "💕", tone: "blush" },
  { gene: "SLC24A4", label: "Gen jasnej karnacji", icon: "🌤️", tone: "ivory" },
  { gene: "SLC45A2", label: "Gen jasnej skóry (MATP)", icon: "🧴", tone: "pearl" },
  { gene: "SCN2A", label: "Gen padaczki i rozwoju", icon: "⚡", tone: "grape" },
  { gene: "SHANK3", label: "Gen Phelan-McDermid", icon: "🔗", tone: "teal" },
  { gene: "SLC6A4", label: "Gen depresji", icon: "🌧️", tone: "storm" },
  { gene: "SNAP25", label: "Gen impulsów", icon: "⚡", tone: "grape" },
  { gene: "SYNGAP1", label: "Gen SYNGAP1-DEE", icon: "🧩", tone: "mint" },
  { gene: "TAS2R38", label: "Gen supersmakosza", icon: "👅", tone: "grape" },
  { gene: "TPH2", label: "Gen miłych gości", icon: "😊", tone: "honey" },
  { gene: "TSC1", label: "Gen hamartyny (TSC)", icon: "🔬", tone: "sage" },
  { gene: "TSC2", label: "Gen tuberyny (TSC)", icon: "🔬", tone: "forest" },
  { gene: "VDR", label: "Gen receptora witaminy D", icon: "☀️", tone: "sun" },
  { gene: "VKORC1", label: "Gen warfaryny", icon: "🩸", tone: "wine" },
  { gene: "WWC1", label: "Gen pamięci", icon: "🧠", tone: "gold" },
  { gene: "ZEB2", label: "Gen naczyń i Mowata-Wilsona", icon: "🩸", tone: "wine" },
  { gene: "ABCB1", label: "Transporter glikoproteiny P", icon: "🧬", tone: "slate" },
  { gene: "ABCB6", label: "Udział w transporcie metabolicznym w OUN.", icon: "🧬", tone: "slate" },
  { gene: "ADGRL3", label: "Tworzenie synaps glutamatergicznych, wzrost neurytów.", icon: "🧬", tone: "slate" },
  { gene: "AKAP11", label: "Sygnalizacja kinaz, interakcja z GSK3B (cel dla litu).", icon: "🧬", tone: "slate" },
  { gene: "AKT3", label: "Kinaza białkowa B", icon: "🧬", tone: "slate" },
  { gene: "ALMS1", label: "Rola alternatywnego splicingu w wyznaczaniu deficytów b…", icon: "🧬", tone: "slate" },
  { gene: "ANK2", label: "Organizacja synaps, transport pęcherzyków.", icon: "🧬", tone: "slate" },
  { gene: "ARID1B", label: "Kompleks SWI/SNF, transkrypcja.", icon: "🧬", tone: "slate" },
  { gene: "ARTN", label: "Artemina", icon: "🧬", tone: "slate" },
  { gene: "ASTN2", label: "Migracja neuronów", icon: "🧬", tone: "slate" },
  { gene: "ATP2A2", label: "Pompa wapniowa siateczki (SERCA2)", icon: "🧬", tone: "slate" },
  { gene: "BCL11B", label: "Regulator różnicowania komórek T i funkcji prążkowia.", icon: "🧬", tone: "slate" },
  { gene: "C1R", label: "Układ dopełniacza", icon: "🧬", tone: "slate" },
  { gene: "C4A", label: "Układ dopełniacza", icon: "🧬", tone: "slate" },
  { gene: "CACNB2", label: "Pomocnicza podjednostka kanału wapniowego", icon: "🧬", tone: "slate" },
  { gene: "CBS", label: "Syntaza cystationiny-beta. Homocystynuria z fenotypem a…", icon: "🧬", tone: "slate" },
  { gene: "CHD8", label: "Remodelowanie chromatyny, makrocefalia.", icon: "🧬", tone: "slate" },
  { gene: "CHRNA2", label: "Receptor nikotynowy acetylocholiny", icon: "🧬", tone: "slate" },
  { gene: "CHRNA4", label: "Receptor nikotynowy", icon: "🧬", tone: "slate" },
  { gene: "CHRNA7", label: "Receptor nikotynowy", icon: "🧬", tone: "slate" },
  { gene: "CNR1", label: "Receptor kanabinoidowy CB1", icon: "🧬", tone: "slate" },
  { gene: "CRHR1", label: "Receptor czynnika uwalniającego kortykotropinę typu 1", icon: "🧬", tone: "slate" },
  { gene: "CRP", label: "Koduje białko C-reaktywne", icon: "🧬", tone: "slate" },
  { gene: "CSMD1", label: "Kaskada dopełniacza (odporność)", icon: "🧬", tone: "slate" },
  { gene: "CYP2B6", label: "Metabolizm bupropionu i mirtazapiny.", icon: "🧬", tone: "slate" },
  { gene: "CYP3A4", label: "Odpowiadają za tempo eliminacji trójpierścieniowych (TC…", icon: "🧬", tone: "slate" },
  { gene: "CYREN", label: "Naprawa DNA i ochrona genomu neuronalnego (mózg dorosły…", icon: "🧬", tone: "slate" },
  { gene: "DCC", label: "Receptor naprowadzania aksonów", icon: "🧬", tone: "slate" },
  { gene: "DHFR", label: "Reduktaza dihydrofolianu. Zaburzenia remetylacji, objaw…", icon: "🧬", tone: "slate" },
  { gene: "DRD4", label: "Receptor D4", icon: "🧬", tone: "slate" },
  { gene: "DRD5", label: "Receptor D5", icon: "🧬", tone: "slate" },
  { gene: "DUSP6", label: "Regulacja sygnalizacji ERK/MAPK, stabilność obwodów.", icon: "🧬", tone: "slate" },
  { gene: "DYRK1A", label: "Proliferacja neuronów, neurogeneza.", icon: "🧬", tone: "slate" },
  { gene: "FOXP2", label: "Neurogeneza, rozwój mowy, komunikacja neuronalna.", icon: "🧬", tone: "slate" },
  { gene: "FURIN", label: "Przetwarzanie pro-białek (w tym BDNF)", icon: "🧬", tone: "slate" },
  { gene: "GABBR2", label: "Receptor GABA typu B", icon: "🧬", tone: "slate" },
  { gene: "GADL1", label: "System glutaminergiczny", icon: "🧬", tone: "slate" },
  { gene: "GOLPH3L", label: "Funkcja aparatu Golgiego", icon: "🧬", tone: "slate" },
  { gene: "GPR151", label: "Receptor sierocy", icon: "🧬", tone: "slate" },
  { gene: "GRIA2", label: "Receptor AMPA", icon: "🧬", tone: "slate" },
  { gene: "GRIN2A", label: "Podjednostka receptora NMDA", icon: "🧬", tone: "slate" },
  { gene: "GRIN2B", label: "Neurotransmisja glutaminianergiczna.", icon: "🧬", tone: "slate" },
  { gene: "GRM3", label: "Metabotropowy receptor glutaminianu 3", icon: "🧬", tone: "slate" },
  { gene: "GRM5", label: "Receptor glutaminianu", icon: "🧬", tone: "slate" },
  { gene: "GSK3B", label: "Kinaza syntazy glikogenu 3-beta", icon: "🧬", tone: "slate" },
  { gene: "HCN1", label: "Kanał aktywowany hiperpolaryzacją", icon: "🧬", tone: "slate" },
  { gene: "HRH3", label: "Receptor histaminowy H3", icon: "🧬", tone: "slate" },
  { gene: "HTR1B", label: "Receptor 1B", icon: "🧬", tone: "slate" },
  { gene: "HTR2A", label: "Receptor 2A", icon: "🧬", tone: "slate" },
  { gene: "HTR4", label: "Receptor 4", icon: "🧬", tone: "slate" },
  { gene: "HTR6", label: "Receptor serotoninowy", icon: "🧬", tone: "slate" },
  { gene: "IDO1", label: "Enzym szlaku kynureninowego", icon: "🧬", tone: "slate" },
  { gene: "IL6", label: "Cytokina prozapalna", icon: "🧬", tone: "slate" },
  { gene: "KCNN2", label: "Kanały potasowe", icon: "🧬", tone: "slate" },
  { gene: "KCNQ3", label: "Kanał potasowy, stabilizacja potencjału błonowego neuro…", icon: "🧬", tone: "slate" },
  { gene: "KMO", label: "Monooksygenaza kynureninowa", icon: "🧬", tone: "slate" },
  { gene: "KMT2D", label: "Zespół Kabuki. Specyficzna dysmorfia twarzy, wady serca…", icon: "🧬", tone: "slate" },
  { gene: "LINC01795", label: "Długie niekodujące RNA", icon: "🧬", tone: "slate" },
  { gene: "LSM6", label: "Stabilna ekspresja w neuronach pobudzających i hamujący…", icon: "🧬", tone: "slate" },
  { gene: "MACROD2", label: "Rozwój poznawczy i mowa.", icon: "🧬", tone: "slate" },
  { gene: "MAPT", label: "Region h2 (inwersja)", icon: "🧬", tone: "slate" },
  { gene: "MC4R", label: "Receptor melanokortyny 4\. Kontrola apetytu.", icon: "🧬", tone: "slate" },
  { gene: "MCHR1", label: "Sygnalizacja hormonalna i regulacja nastroju.", icon: "🧬", tone: "slate" },
  { gene: "MDFIC", label: "Plejotropia z zachowaniami impulsywnymi i agresją (jądr…", icon: "🧬", tone: "slate" },
  { gene: "MED8", label: "Składnik mediatora transkrypcji, stabilna ekspresja.", icon: "🧬", tone: "slate" },
  { gene: "MEIS1", label: "Regulacja rytmów dobowych i snu.", icon: "🧬", tone: "slate" },
  { gene: "MICA", label: "Aktywacja wrodzonej odpowiedzi odpornościowej w mózgu.", icon: "🧬", tone: "slate" },
  { gene: "MPL", label: "Nowy gen ryzyka związany z podziałami komórkowymi (kora…", icon: "🧬", tone: "slate" },
  { gene: "MSRA", label: "Związek z rozwojem układu nerwowego.", icon: "🧬", tone: "slate" },
  { gene: "NAGA", label: "Metabolizm glikolipidów i glikoprotein.", icon: "🧬", tone: "slate" },
  { gene: "NCAM1", label: "Sygnalizacja RET/NCAM", icon: "🧬", tone: "slate" },
  { gene: "NCAN", label: "Białko macierzy", icon: "🧬", tone: "slate" },
  { gene: "NEGR1", label: "Adhezja komórek neuronalnych", icon: "🧬", tone: "slate" },
  { gene: "NEK4", label: "Kinaza", icon: "🧬", tone: "slate" },
  { gene: "NKX2-2", label: "Różnicowanie gleju", icon: "🧬", tone: "slate" },
  { gene: "NR3C1", label: "Receptor glikokortykoidowy", icon: "🧬", tone: "slate" },
  { gene: "NR3C2", label: "Receptor mineralokortykoidowy", icon: "🧬", tone: "slate" },
  { gene: "NSUN2", label: "Metylo transferaza cytozyny-5 w RNA", icon: "🧬", tone: "slate" },
  { gene: "NSUN6", label: "Metylo transferaza tRNA", icon: "🧬", tone: "slate" },
  { gene: "PCDHG", label: "Klaster protokadheryn", icon: "🧬", tone: "slate" },
  { gene: "PDE4B", label: "Fosfodiesteraza 4B", icon: "🧬", tone: "slate" },
  { gene: "POU3F2", label: "Czynnik transkrypcyjny regulujący różnicowanie neuronów…", icon: "🧬", tone: "slate" },
  { gene: "PROZ", label: "Białko Z", icon: "🧬", tone: "slate" },
  { gene: "PTEN", label: "Zespół Cowden. Makrocefalia, polipy, ryzyko nowotworów.", icon: "🧬", tone: "slate" },
  { gene: "PTPRE", label: "Fosfataza tyrozynowa", icon: "🧬", tone: "slate" },
  { gene: "PTPRF", label: "Wpływ na stabilność synaps (kora płodowa i dorosła).", icon: "🧬", tone: "slate" },
  { gene: "QTRT1", label: "Maszyneria modyfikacji tRNA.", icon: "🧬", tone: "slate" },
  { gene: "RET", label: "Sygnalizacja RET/NCAM", icon: "🧬", tone: "slate" },
  { gene: "RIMS1", label: "Funkcje komponentów synaptycznych.", icon: "🧬", tone: "slate" },
  { gene: "RORB", label: "Regulacja rytmów dobowych i snu.", icon: "🧬", tone: "slate" },
  { gene: "RPS26", label: "Biogeneza rybosomów, ekspresja w mózgu płodowym.", icon: "🧬", tone: "slate" },
  { gene: "SESTD1", label: "Domena SEC14 i spektryny", icon: "🧬", tone: "slate" },
  { gene: "SHISA9", label: "Regulator receptorów AMPA, plastyczność synaptyczna w P…", icon: "🧬", tone: "slate" },
  { gene: "SLC12A5", label: "Wraz z GRIN2A i GRM3 wpływa na system NMDA/Glutaminian.", icon: "🧬", tone: "slate" },
  { gene: "SLC4A1", label: "Transporter jonowy", icon: "🧬", tone: "slate" },
  { gene: "SLC6A2", label: "Transporter noradrenaliny (NET)", icon: "🧬", tone: "slate" },
  { gene: "SLC6A3", label: "Transporter dopaminy. Zaburzenia korelują ze spowolnien…", icon: "🧬", tone: "slate" },
  { gene: "SORCS3", label: "Plastyczność synaptyczna. Wspólny czynnik z autyzmem i …", icon: "🧬", tone: "slate" },
  { gene: "SOX7", label: "Związek z rozwojem układu nerwowego.", icon: "🧬", tone: "slate" },
  { gene: "ST3GAL3", label: "Enzym glikozylacji", icon: "🧬", tone: "slate" },
  { gene: "STX16-NPEPL1", label: "Fuzja genowa", icon: "🧬", tone: "slate" },
  { gene: "TCF4", label: "Zespół Pitta-Hopkinsa. Głębokie opóźnienie rozwoju, hip…", icon: "🧬", tone: "slate" },
  { gene: "TDO2", label: "Podobnie jak IDO1, przekierowuje metabolizm tryptofanu …", icon: "🧬", tone: "slate" },
  { gene: "THSD7A", label: "Adhezja komórkowa w mózgu.", icon: "🧬", tone: "slate" },
  { gene: "TIE1", label: "Receptorowa kinaza tyrozynowa, rozwój naczyniowy mózgu.", icon: "🧬", tone: "slate" },
  { gene: "TMEM140", label: "Białko transbłonowe", icon: "🧬", tone: "slate" },
  { gene: "TNFA", label: "Czynnik martwicy nowotworu", icon: "🧬", tone: "slate" },
  { gene: "TRANK1", label: "Sygnalizacja komórkowa", icon: "🧬", tone: "slate" },
  { gene: "TRMT61A", label: "Metylo transferaza katalizująca modyfikacje w tRNA.", icon: "🧬", tone: "slate" },
  { gene: "TYW5", label: "Modyfikacja tRNA powiązana ze stabilnością funkcji pozn…", icon: "🧬", tone: "slate" },
  { gene: "UBE3A", label: "Zespół Angelmana. Ataksja, brak mowy, napady śmiechu.", icon: "🧬", tone: "slate" },
  { gene: "USP35", label: "Peptydaza regulująca obrót białek w synapsach.", icon: "🧬", tone: "slate" },
  { gene: "ZSWIM6", label: "Rola w tworzeniu połączeń neuronalnych.", icon: "🧬", tone: "slate" },
];
